name: Upload we

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync to S3
        run: |
          aws s3 mb s3://bigdata113

        env:
          AWS_ACCESS_KEY_ID: ASIA3AWNGJFYWSAATR2T
          AWS_SECRET_ACCESS_KEY: YEmWybLIWgMnfPTz9QqRevd2z4doDPg5KwiuOgba
          AWS_SESSION_TOKEN: FwoGZXIvYXdzEDIaDFMuQjUEj51xSzM+AiLOASdUJ+G2R1D3iSDs1BoCMLWVMrp4SiRoPr5UPeg8lEBwjG2RkNbZxlHTeBjCct9XhSW+EraS9zvuPvJCX8OmilbMzroa8l6ItEGUmY4blc+v3erEnMhMnUQeZAggYS6J/gnxQ3qFTKzO072UWsRK6RUBNgkSpGix8hznyrCd+rTOw/CaICoWe7FFF05scy61y/ICQ1AdXrZR2Yu/+0wW+LKo9H5pMaRBGWTR/jKdDUxvspLINXV2/Tz3VxxdMEwZRWHgf4oclUuU9hdxXGO+KMWgkq4GMi3wx7heFbBuvViEBfCmCNK7avPC9aAwZyqwxC7ZjoiDqE+0MSW9AnZCPBSQxAw=
          AWS_DEFAULT_REGION: us-east-1